<a href="https://colab.research.google.com/github/Ansh8565/Notebooks/blob/main/r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import pandas as pd

students <-data.frame(
  name=c("Ansh","Langda","Bauna"),
  age= c(25,23,5),
  marks= c(80,70,10)
)
students

  name   age marks
1 Ansh   25  80
2 Langda 23  70
3 Bauna   5  10

In [ ]:
data(iris)

In [ ]:
# head(iris)
# names(iris)
# str(iris)
# dim(iris)
summary(students)

        name        age            marks
 Length   :3   Min.   : 5.00   Min.   :10.00
 N.unique :3   1st Qu.:14.00   1st Qu.:40.00
 N.blank  :0   Median :23.00   Median :70.00
 Min.nchar:4   Mean   :17.67   Mean   :53.33
 Max.nchar:6   3rd Qu.:24.00   3rd Qu.:75.00
               Max.   :25.00   Max.   :80.00


**CARET**
(same as scikit- learn)

In [ ]:
install.packages("caret")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘listenv’, ‘parallelly’, ‘future’, ‘globals’, ‘shape’, ‘future.apply’, ‘numDeriv’, ‘progressr’, ‘SQUAREM’, ‘diagram’, ‘lava’, ‘prodlim’, ‘proxy’, ‘iterators’, ‘clock’, ‘gower’, ‘hardhat’, ‘ipred’, ‘sparsevctrs’, ‘timeDate’, ‘e1071’, ‘foreach’, ‘ModelMetrics’, ‘plyr’, ‘pROC’, ‘recipes’, ‘reshape2’

In [ ]:
students<- data.frame(
  hours=c(1,2,3,4,5,6,7,8,9),
  marks=c(35,46,46,22,3,3,1,77,88)
)

In [ ]:
set.seed(123)

In [ ]:
index<-simple()

ERROR: Error in simple(): could not find function "simple"

In [ ]:
index<-sample(
  1:nrow(students),
  8
)

In [ ]:
train_data<-students[index,]

ERROR: Error: object 'index' not found

In [ ]:
test_data<-students[-index,]

In [ ]:
predict<-predict(model,newdata=test_data)

ERROR: Error: object 'model' not found

In [ ]:
print(predict)

function (object, ...)
UseMethod("predict")
<bytecode: 0x5618f0a08540>
<environment: namespace:stats>

In [ ]:
houses <- data.frame(
  area = c(500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400),
  price = c(20, 24, 28, 32, 36, 40, 44, 48, 53, 57)
)

In [ ]:
houses

In [ ]:
set.seed(123)
train_set <- sample(1:nrow(houses), 8)

In [ ]:
train_data <- houses[train_set, ]
test_data <- houses[-train_set, ]

In [ ]:
install.packages("mlr3")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘nanonext’, ‘PRROC’, ‘checkmate’, ‘lgr’, ‘mirai’, ‘mlbench’, ‘mlr3measures’, ‘mlr3misc’, ‘palmerpenguins’, ‘paradox’

In [ ]:
install.packages("mlr3learners")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(mlr3)

In [ ]:
library(mlr3learners)

In [ ]:
students <- data.frame(
  hours=c(1,2,3,4,5,6,7,8,9,10),
  result=factor(c(
    "Fail","Fail","Fail","Fail","Pass",
    "Pass","Pass","Pass","Pass","Pass"
  ))
)
students

   hours result
1   1    Fail
2   2    Fail
3   3    Fail
4   4    Fail
5   5    Pass
6   6    Pass
7   7    Pass
8   8    Pass
9   9    Pass
10 10    Pass

In [ ]:
task<- as_task_classif(
  students,
  target="result"
)

In [ ]:
learner <- lrn("classif.log_reg")

In [ ]:
learner$train(task)

In [ ]:
new_student <-data.frame(
  hours=3
)

In [ ]:
prediction <- learner$predict_newdata(new_student)
prediction$response

[1] Fail
Levels: Fail Pass

Load the mtCars dataset and display the first 6 rows.
How many rows and columns are present in mtCars.
data(mtCars)
head(mtCars)

In [ ]:
data(mtcars)